openapi: 3.0.3
info:
  title: sample
  version: '1.0'
servers:
  - url: http://localhost:8000
paths:
  "/api/analyzed":
    get:
      operationId: fetchData
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Historys"
components:
  schemas:
    Historys:
      description: weather data
      type: Array
      items:
        $ref: "#/components/schemas/History"
    History:
        type: object
        properties:
          id:
              type: integer
              format: int32
          weather_id:
              type: integer
              format: int32
          icon_id:
              type: string
          city_name:
              type: string
          city_id: 
              type: integer
              format: int32
          main: 
              type: string
          main_description: 
              type: string
          temp_min: 
              type: integer
              format: int32
          temp_max: 
              type: integer
              format: int32
          pressure: 
              type: integer
              format: int32
          humidity: 
              type: integer
              format: int32
          wind_speed: 
              type: integer
              format: int32
          date: 
              type: string
              format: date
          created_at: 
              type: string
              format: date-time
        required:
          - id
          - date
          - created_at