/* tslint:disable */
/* eslint-disable */
/**
 * sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface History
 */
export interface History {
    /**
     * 
     * @type {number}
     * @memberof History
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof History
     */
    'weather_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof History
     */
    'icon_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof History
     */
    'city_name'?: string;
    /**
     * 
     * @type {number}
     * @memberof History
     */
    'city_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof History
     */
    'main'?: string;
    /**
     * 
     * @type {string}
     * @memberof History
     */
    'main_description'?: string;
    /**
     * 
     * @type {number}
     * @memberof History
     */
    'temp_min'?: number;
    /**
     * 
     * @type {number}
     * @memberof History
     */
    'temp_max'?: number;
    /**
     * 
     * @type {number}
     * @memberof History
     */
    'pressure'?: number;
    /**
     * 
     * @type {number}
     * @memberof History
     */
    'humidity'?: number;
    /**
     * 
     * @type {number}
     * @memberof History
     */
    'wind_speed'?: number;
    /**
     * 
     * @type {string}
     * @memberof History
     */
    'date': string;
    /**
     * 
     * @type {string}
     * @memberof History
     */
    'created_at': string;
}

